title:       "netzfisch's ...wikibrain and blogtaker"
url:         http://netzfisch.github.io/
author:      netzfisch
email:       tweet@me
description: "some things that matter to me, mostly tech stuff: linux, ruby, rails, gadgets ... open source ... travel pics"

safe:        false 
auto:        false
server:      false

# source:      ./
# destination: ./_site
plugins:     ./_plugins

future:      false
lsi:         false 
pygments:    true
markdown:    maruku
permalink:   date

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
