title:       "netzfisch's ...wikibrain and blogtaker"
url:         http://netzfisch.github.com
author:      netzfisch
email:       tweet@me

safe:        false 
auto:        false
server:      false

# source:      ./
# destination: ./_site
plugins:     ./_plugins

future:      false
lsi:         false
pygments:    true
markdown:    maruku
permalink:   date

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
