safe: false
auto: false
server: false

plugins: ./_plugins

future: false
lsi: true
pygments: true
markdown: maruku
permalink: date

tage_layout: default
tag_page_dir: tag

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
