safe:        false 
auto:        true
server:      true

#source:      ./
#destination: ./_site
plugins:     ./_plugins

future:      false
lsi:         false
pygments:    true
markdown:    maruku
permalink:   date

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
